var GAME_LEVELS = [
  ["                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                   xxxxx                                                                               ",
   "                                  xxxxxxx                                                      xxxxx                   ",
   "                                 xxxpppxxx                          o                          xxqxx                   ",
   "                                 xxxpppxxx                          x                          xx xx                   ",
   "                    xxx                                                                                                ",
   "                    xqx                                                     xx                            oo           ",
   "      @                                                                            p                      xx           ",
   "     xx                                                                x                  x             xx             ",
   "  x                                                                                  x                                 ",
   "  x           o                                             x    x          x                x      x                  ",
   "  x          xxxx                                   xx                                          x                      ",
   "  x          x  x                 s  o  s       ss            s     s     s         x                                  ",
   "  xxx!!!!xxxxx  xxxx   o   xxxxxxxxxxxxxxxxxxxxxxx     oo     xxxxxxx!!!!!xxxxxxxxxsssssssssss                        s",
   "     !!!!          x   x   x                     x     xx    xx      !!!!!        xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!x",
   "     !!!!          xsssssssx                     xsssssssssssx       !!!!!                   x!!!!!!!!!!!!!!!!!!!!!!!!x",
   "     !!!!          xxxxxxxxx                     xsssssssssssx       !!!!!                   x!!!!!!!!!!!!!!!!!!!!!!!!x",
   "     !!!!                                        xxxxxxxxxxxxx       !!!!!                   x!!!!!!!!!!!!!!!!!!!!!!!!x",
   "     !!!!                                                                                    xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "     !!!!                                                                                                              "],
  ["                                                                                                                        ",
   "                                                                                                                        ",
   "                                                                                                                        ",
   "                                                                                                                        ",
   "                                                                                                                        ",
   "                                                 xxx                                                                    ",
   "      xxx                                        xqx          ssssssssssssss                                            ",
   "      xpx                                                     xxxxxxxxxxxxxx                                            ",
   "                 sss                                          xxxxxqqqqxxxxx                                            ",
   "                xxxxx                                          xxxx     xxxx                                             ",
   "                xpppx                                                                                                   ",
   "                x   x                                                                                                   ",
   "                                                                                                                        ",
   "                                                                                                                        ",
   "                                                                             p p p p p p                                ",
   "                   o                               o  o                     p p p p p p p                               ",
   "      @         sxxxxxxx       o                                                                                        ",
   "      xx     xxxxx    xxxx                          x                                                                   ",
   "!!!!!!!!!!!!!x        xxxxx                o                                                                            ",
   "!!!!!!!!!!!!!x        xxxxssssssssxx              xx        xx   x                                                      ",
   "!!!!!!!!!!!!!x        xxxxxxxxxxxxxx            xxx        xx        o                                                  ",
   "!!!!!!!!!!!!!x        x!!!!!!!!!!!xxx         xxxx        xx         x    x                                             ",
   "!!!!!!!!!!!!!x        x!!!!!!!!!!!xxxxxx!!!!!!xxx        xx!!!!!!!!!        s                   oo                      ",
   "!!!!!!!!!!!!!x        x!!!!!!!!!!!x    xxxxxxxxx        xx!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxx    xx                      ",
   "!!!!!!!!!!!!!x        x!!!!!!!!!!xx o                xxxxx!!!!!!!!!!!!!!!!!!              xssssssssssssx                ",
   "!!!!!!!!!!!!!x        x!!!!!!!!!!x                   xxxx!!!!!!!!!!!!!!!!!!!              xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!x        x!!!!!!!!!!x                   xxxx!!!!!!!!!!!!!!!!!!!                            !!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!x        x!!!!!!!!!!xssssxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!                           !!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!x        !!!!!!!!!!!xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                                  "]
  ["                                                                                                              ",
   "                                                                     xxxxxxx                                  ",
   "                                                                     xxqqqxx                                  ",
   "                                                                     xxqqqxx                                  ",
   "                                                                                                              ",
   "                                                              o                                               ",
   "                                                            xxxxx                                             ",
   "                                                            xxxxx                                             ",
   "                                                          xxxxxxx                                           ",
   "                                                            xxxxx                                             ",
   "                                                   x        xxxxx                                             ",
   "                                                            xxxxx                                            ",
   "                                                          xxxxxxx                                            ",
   "                                                            xqqqx                                            ",
   "                                                            x   x                                            ",
   "                                                      x     x   x                                            ",
   "                                                            x   x                                             ",
   "                                                            x   xx                                           ",
   "                                                           xx                                                ",
   "                                                  o   o   x                                                   ",
   "                      xxxxxx                      x   x       o                                               ",
   "                     xxqqqqxx                xx s x s x s xx  x                                               ",
   "                                            xxxxxxxxxxxxxxxx ssssx      s                                    ",
   "                    x                      x       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "   @             o                       xx         xxxqqqxxx        xppx                                     ",
   "  xxx    xxx    xxx                   x                                                      o                ",
   "  x                      o         x                                                        xxx               ",
   "  x                             x                                                                             ",
   "  x!!!!!!!!!!!!x                                                                    xxx                       ",
   "  x!!!!!!!!!!!!xxssssssssssxxxx!!!!!!!!!!!!!xxxxx                                                             ",
   "  x!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxx                      o       xxxx                            ",
   "  x!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxx   o                     xx                                  ",
   "  x!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxx   x       sxxxs                                              ",
   "  x!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxx                                                             ",
   "  x!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  x!!!!!!!!!!!!xxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx             !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "                                                                                                              ",
   "                                                                                                              "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
